# Import Financial Data

In [9]:
from datetime import datetime
import MetaTrader5 as mt5
import pandas as pd

In [10]:
mt5.initialize()

True

### IMPORT TICKS DATA

##### Import ticks from

In [11]:
# Import ticks from a date to 

# Compute now date
from_date = datetime.now()

# Extract n Ticks before now
mt5.copy_ticks_from("EURUSD", from_date, 10, mt5.COPY_TICKS_ALL)

array([(1779132310, 1.16536, 1.16542, 0., 0, 1779132310080, 1028, 0.),
       (1779132310, 1.16537, 1.16539, 0., 0, 1779132310373, 1158, 0.),
       (1779132310, 1.1653 , 1.16539, 0., 0, 1779132310491, 1154, 0.),
       (1779132310, 1.16533, 1.16539, 0., 0, 1779132310671, 1154, 0.),
       (1779132311, 1.16531, 1.16539, 0., 0, 1779132311517, 1154, 0.),
       (1779132312, 1.16536, 1.16538, 0., 0, 1779132312822, 1158, 0.),
       (1779132316, 1.16535, 1.16537, 0., 0, 1779132316434, 1158, 0.),
       (1779132316, 1.16536, 1.16538, 0., 0, 1779132316936, 1158, 0.),
       (1779132317, 1.16535, 1.16537, 0., 0, 1779132317210, 1158, 0.),
       (1779132317, 1.16536, 1.16538, 0., 0, 1779132317861, 1158, 0.)],
      dtype=[('time', '<i8'), ('bid', '<f8'), ('ask', '<f8'), ('last', '<f8'), ('volume', '<u8'), ('time_msc', '<i8'), ('flags', '<u4'), ('volume_real', '<f8')])

In [12]:
# Compute now date


# Compute now date
from_date = datetime.now()

# Extract n Ticks before now
ticks = mt5.copy_ticks_from("EURUSD", from_date, 10, mt5.COPY_TICKS_ALL)

# Transfrom a tuple into a dataframe
df_ticks = pd.DataFrame(ticks)

# Convert number format of the date into date format
df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")

df_ticks

,time,bid,ask,last,volume,time_msc,flags,volume_real
0,05/18/2026 03:25:10 PM,1.16536,1.16542,0.0,0,1779132310080,1028,0.0
1,05/18/2026 03:25:10 PM,1.16537,1.16539,0.0,0,1779132310373,1158,0.0
2,05/18/2026 03:25:10 PM,1.16530,1.16539,0.0,0,1779132310491,1154,0.0
3,05/18/2026 03:25:10 PM,1.16533,1.16539,0.0,0,1779132310671,1154,0.0
4,05/18/2026 03:25:11 PM,1.16531,1.16539,0.0,0,1779132311517,1154,0.0
5,05/18/2026 03:25:12 PM,1.16536,1.16538,0.0,0,1779132312822,1158,0.0
6,05/18/2026 03:25:16 PM,1.16535,1.16537,0.0,0,1779132316434,1158,0.0
7,05/18/2026 03:25:16 PM,1.16536,1.16538,0.0,0,1779132316936,1158,0.0
8,05/18/2026 03:25:17 PM,1.16535,1.16537,0.0,0,1779132317210,1158,0.0
9,05/18/2026 03:25:17 PM,1.16536,1.16538,0.0,0,1779132317861,1158,0.0

##### Import ticks Range

In [13]:
# Compute now date
from_date = datetime(2022,1,5)
to_date = datetime(2022,1,6)

# Extract n Ticks before now
ticks = mt5.copy_ticks_range("EURUSD", from_date, to_date, mt5.COPY_TICKS_ALL)

# Transfrom a tuple into a dataframe
df_ticks = pd.DataFrame(ticks)

# Convert number format of the date into date format
df_ticks["time"] = pd.to_datetime(df_ticks["time"], unit="s")

df_ticks

,time,bid,ask,last,volume,time_msc,flags,volume_real
0,01/05/2022 12:00:00 AM,1.12920,1.12926,0.0,0,1641358800655,130,0.0
1,01/05/2022 12:00:00 AM,1.12922,1.12928,0.0,0,1641358800763,134,0.0
2,01/05/2022 12:00:00 AM,1.12925,1.12926,0.0,0,1641358800887,134,0.0
3,01/05/2022 12:00:01 AM,1.12926,1.12927,0.0,0,1641358801123,134,0.0
4,01/05/2022 12:00:03 AM,1.12922,1.12928,0.0,0,1641358803840,134,0.0
...,...,...,...,...,...,...,...,...
66015,01/05/2022 11:59:57 PM,1.13187,1.13193,0.0,0,1641445197013,134,0.0
66016,01/05/2022 11:59:58 PM,1.13191,1.13192,0.0,0,1641445198158,134,0.0
66017,01/05/2022 11:59:58 PM,1.13190,1.13191,0.0,0,1641445198498,134,0.0
66018,01/05/2022 11:59:59 PM,1.13191,1.13192,0.0,0,1641445199656,134,0.0
66019,01/05/2022 11:59:59 PM,1.13190,1.13191,0.0,0,1641445199912,134,0.0

### IMPORT RATES DATA

##### Import rates from

In [14]:
# Compute now date
from_date = datetime.now()

# Extract n Ticks before now
rates = mt5.copy_rates_from("EURUSD", mt5.TIMEFRAME_H1, from_date, 15)

# Transform Tuple into a DataFrame
df_rates = pd.DataFrame(rates)

# Convert number format of the date into date format
df_rates["time"] = pd.to_datetime(df_rates["time"], unit="s")

df_rates

,time,open,high,low,close,tick_volume,spread,real_volume
0,05/18/2026 01:00:00 AM,1.16173,1.16196,1.16125,1.16155,2719,0,0
1,05/18/2026 02:00:00 AM,1.16155,1.16225,1.16148,1.16218,2408,2,0
2,05/18/2026 03:00:00 AM,1.16218,1.16261,1.16180,1.16207,2551,2,0
3,05/18/2026 04:00:00 AM,1.16207,1.16232,1.16156,1.16231,3071,2,0
4,05/18/2026 05:00:00 AM,1.16231,1.16365,1.16219,1.16356,4574,0,0
5,05/18/2026 06:00:00 AM,1.16356,1.16400,1.16308,1.16319,4531,0,0
6,05/18/2026 07:00:00 AM,1.16319,1.16452,1.16284,1.16415,4247,1,0
7,05/18/2026 08:00:00 AM,1.16415,1.16427,1.16345,1.16350,3055,0,0
8,05/18/2026 09:00:00 AM,1.16349,1.16367,1.16258,1.16269,2853,2,0
9,05/18/2026 10:00:00 AM,1.16268,1.16496,1.16264,1.16416,7017,0,0
10,05/18/2026 11:00:00 AM,1.16416,1.16572,1.16400,1.16513,7841,0,0
11,05/18/2026 12:00:00 PM,1.16513,1.16560,1.16429,1.16506,6645,0,0
12,05/18/2026 01:00:00 PM,1.16506,1.16532,1.16402,1.16418,7450,0,0
13,05/18/2026 02:00:00 PM,1.16418,1.16529,1.16324,1.16484,7185,0,0
14,05/18/2026 03:00:00 PM,1.16484,1.16562,1.16431,1.16514,5573,0,0

##### Import rates range

In [15]:
# Compute now date
from_date = datetime(2022,1,1)
to_date = datetime(2022,1,10)

# Extract n Ticks before now
rates = mt5.copy_rates_range("EURUSD", mt5.TIMEFRAME_H1, from_date, to_date)

# Transform Tuple into a DataFrame
df_rates = pd.DataFrame(rates)

# Convert number format of the date into date format
df_rates["time"] = pd.to_datetime(df_rates["time"], unit="s")

df_rates

,time,open,high,low,close,tick_volume,spread,real_volume
0,01/02/2022 07:00:00 PM,1.13693,1.13742,1.13645,1.13726,571,17,0
1,01/02/2022 08:00:00 PM,1.13725,1.13778,1.13687,1.13728,1345,7,0
2,01/02/2022 09:00:00 PM,1.13728,1.13759,1.13608,1.13622,1054,0,0
3,01/02/2022 10:00:00 PM,1.13622,1.13654,1.13497,1.13588,1349,0,0
4,01/02/2022 11:00:00 PM,1.13588,1.13589,1.13422,1.13427,1091,0,0
...,...,...,...,...,...,...,...,...
121,01/09/2022 08:00:00 PM,1.13560,1.13599,1.13492,1.13532,1216,6,0
122,01/09/2022 09:00:00 PM,1.13532,1.13579,1.13515,1.13549,818,0,0
123,01/09/2022 10:00:00 PM,1.13549,1.13563,1.13497,1.13502,706,0,0
124,01/09/2022 11:00:00 PM,1.13503,1.13520,1.13392,1.13396,809,0,0
125,01/10/2022 12:00:00 AM,1.13396,1.13397,1.13339,1.13376,617,0,0